### ISSUE TITLE
Getting all fields with the same name

### ISSUE THREAD

**Issue by gonzus** [CloudQuote/faux-mysql-server#3]
[I apologize for opening an issue for something that is probably more of an error on my end, but I have not been able to find exactly what's going on and I don't have any other means of communication.]

I have a toy table of continents with columns `id` and `name`. I connect to the faux server and issue the query `select * from continents`. The server does send back two `newDefinitions`, one called `id` and one called `name`, and later send 6 rows of data. However, the client prints the rows of data as:
```
mysql> select * from continents;
+-------+------------+
| id    | id         |
+-------+------------+
|     1 |     Europe |
|     2 |       Asia |
|     3 |    America |
|     4 |     Africa |
|     5 |    Oceania |
|     6 | Antarctica |
+-------+------------+
6 rows in set (0.01 sec)
```

If I connect to a real MySQL server (which has the same data in it), and run the same query, I get:
```
mysql> select * from continents order by id;
+----+------------+
| id | name       |
+----+------------+
|  1 | Europe     |
|  2 | Asia       |
|  3 | America    |
|  4 | Africa     |
|  5 | Oceania    |
|  6 | Antarctica |
+----+------------+
6 rows in set (0.00 sec)
```

The main issue I am having is getting those incorrect column names; when the table has more than one column, all of the columns I get end up having the same name as the first column. This could cause real problems, since some ORMs use the column name to create the key for the column: `[{id: 4, name: "Africa"}, ...]`.

You can also see some other differences, which might or might not point to actual problems. In the results shown for the real MySQL server:
* The `id` column is narrower.
* The `name` column is left-justified and narrower.

I would be happy to hear any suggestions you may have.

**Comment by gonzus** [comment]
Something else I want to add on a separate comment. I have been using wireshark (actually, tshark) to look at the data flow for real vs faux MySQL, and there is definitely something in the responses from faux that doesn't allow tshark to decode the packets properly. For example, this is the capture for the query mentioned above, for real MySQL:
```
$ export PORT=3306; tshark -i lo -d tcp.port==$PORT,mysql -T fields -e mysql.query -e mysql.payload -e mysql.num_fields -e mysql.schema -e mysql.field.table -e mysql.field.name -e mysql.field.type -e mysql.field.length -e mysql.field.flags -e mysql.field.flags.primary_key -e mysql.field.flags.auto_increment -e mysql.field.flags.not_null "port $PORT"
Capturing on 'Loopback: lo'
select * from continents order by id											
											
	0000	2		continents,continents	id,name	3,253	10,400	0x00004223,0x00005005	1,0	1,0	1,1
```
However, for the faux server all I get is this:
```
$ export PORT=3344; tshark -i lo -d tcp.port==$PORT,mysql -T fields -e mysql.query -e mysql.payload -e mysql.num_fields -e mysql.schema -e mysql.field.table -e mysql.field.name -e mysql.field.type -e mysql.field.length -e mysql.field.flags -e mysql.field.flags.primary_key -e mysql.field.flags.auto_increment -e mysql.field.flags.not_null "port $PORT"
Capturing on 'Loopback: lo'
select * from continents											
											
		2									
```
(and there are a bunch of blank lines after that `2`, which means there is data flowing through but it cannot be decoded as MySQL protocol). I can provide any additional details that you think might be useful.

**Comment by mdierolf** [comment]
I have fixed a big with the wrong data being written for the 2nd column.
I have also updated the example to show how you can pass in a column type (it was defaulting to DECIMAL, now it defaults to VARCHAR)

Take a look at the "newDefinition" function - you can specify numerous options to control how fields are displayed/interpreted by the MySQL Client

The underlying protocol always sends results as strings, with display guidance for the SQL client

**Comment by gonzus** [comment]
This is great, I can confirm I see the correct column names again. Thanks! Will close this issue.

I left two comments on your commit.
